Optimised backup scripts

diff --git a/Joomla_scripts/jbackupall b/Joomla_scripts/jbackupall
--- a/Joomla_scripts/jbackupall
+++ b/Joomla_scripts/jbackupall
@@ -14,11 +14,27 @@
 # version
 VERSION=1.0
 
-# start folder where we start searching
-STARTDIR="/Users/$USER/Development/Sites"
+# folder for phpdev configuration
+CONFIG_DIR="${HOME}/.config/phpdev"
+# path to the phpdev configuration file
+CONFIG_FILE="${CONFIG_DIR}/config"
 
-# start folder where we start searching
-STOREPATH="/Users/$USER/Development/Backup/sites"
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
+
+# Check if jfunctions script exists
+if [[ ! -f "${MYPATH}/jfunctions" ]]; then
+    echo "Error: Required script 'jfunctions' not found in ${MYPATH}, Exiting."
+    exit 1
+else
+    # Gather Joomla information
+    source "${MYPATH}/jfunctions"
+fi
 
 # display messages
 SILENT="no"
@@ -31,14 +47,8 @@ MYPATH=$(
 MYNAME=$(basename ${0})
 
 # check if folder for backup storage exists
-if [ ! -d "${STOREPATH}" ]; then
-    echo "Backup directory does not exist!"
-    exit 1
-fi
-
-# Check if jfunctions script exists
-if [[ ! -f "${MYPATH}/jfunctions" ]]; then
-    echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
+if [ ! -d "${SITESBACKUP}" ]; then
+    echo "Backup directory ${SITESBACKUP} does not exist, exiting."
     exit 1
 fi
 
@@ -58,7 +68,7 @@ usage() {
 # show message function
 showmessage() {
     if [ "${SILENT}" == "no" ]; then
-        echo "$1"
+        echo -e "$1"
     fi
 }
 
@@ -78,13 +88,12 @@ while getopts sh opt; do
     esac
 done
 
-showmessage "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
+`showmessage` "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
 
-for DIR in $(find ${STARTDIR} -maxdepth 4 -type d); do
+for DIR in $(find ${ROOTFOLDER} -maxdepth 4 -type d); do
     if [ -f ${DIR}/configuration.php ]; then
         # possible joomla found
-        showmessage " "
-        showmessage "Possible Joomla found at ${DIR}."
+        showmessage "\nPossible Joomla found at ${DIR}."
 
         # Go to website root folder
         cd ${DIR}
@@ -94,9 +103,9 @@ for DIR in $(find ${STARTDIR} -maxdepth 4 -type d); do
 
         # Create backup
         showmessage "Create backup for website ${sitenameclean}."
-        jbackup -t -m -s
-        showmessage "Backup for ${sitenameclean} finished."
+        jbackup -t -s
+        showmessage "Backup for ${sitenameclean} ready."
     fi
 done
 
-showmessage "Your website backups are ready in ${STOREPATH}."
+showmessage "Your website backups are ready in ${SITESBACKUP}."
