Improved display version

diff --git a/Joomla_scripts/jdbdropall b/Joomla_scripts/jdbdropall
--- a/Joomla_scripts/jdbdropall
+++ b/Joomla_scripts/jdbdropall
@@ -15,6 +15,49 @@ VERSION=1.0
 MYPATH=$(cd "$(dirname "$0")"; pwd -P)
 MYNAME=$(basename "$0")
 
+# show message function
+showmessage() {
+    if [ "${SILENT}" == "no" ]; then
+        echo -e "$1"
+    fi
+}
+
+# display usage information
+
+usage() {
+    echo -e "\n${MYNAME} ${VERSION}, written by René Kreijveld.\n"
+    echo -e "Usage: ${MYNAME} [-f] [-s] [-h]\n"
+    echo "-f force, do not ask confirmation before dropping tables."
+    echo "-s silent, no messages will be shown (optional)."
+    echo -e "-h Help. Display this info.\n"
+    echo -e "Run ${MYNAME} at the root of your website, where the configuration.php is.\n"
+    exit 0
+}
+
+# Process the arguments
+SILENT="no"
+FORCE="no"
+while getopts fsh opt; do
+    case "${opt}" in
+    f)
+        FORCE="yes"
+        ;;
+    s)
+        SILENT="yes"
+        ;;
+    h)
+        usage
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        usage
+        ;;
+    esac
+done
+
+# Inform the user about the process and ask confirmation
+showmessage "${MYNAME} ${VERSION}"
+
 # Check if jfunctions script exists
 if [[ ! -f "${MYPATH}/jfunctions" ]]; then
     echo "Error: Required script 'jfunctions' not found in ${MYPATH}. Exiting."
@@ -24,16 +67,16 @@ else
     source "${MYPATH}/jfunctions"
 fi
 
-# Process the arguments
-# Inform the user about the process and ask confirmation
-echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
-echo "This is a Joomla! ${jversion} site."
-read -p "Press Enter to drop all database tables of this website or press Ctrl-C to abort."
+showmessage "This is a Joomla! ${jversion} site."
+
+if [ "${FORCE}" == "no" ]; then
+    read -p "Press Enter to drop all database tables of this website or press Ctrl-C to abort."
+fi
 
 NOW=$(date +".%Y%m%d-%H%M%S")
 TMPFILE="./tmp_drop_all_${NOW}.sql"
 
-echo "Dropping all tables..."
+showmessage "Dropping all tables..."
 
 echo "SET FOREIGN_KEY_CHECKS = 0;" > "${TMPFILE}"
 mariadb-dump --add-drop-table --no-data --host="${host}" --user="${dbuser}" --password="${password}" "${database}" | grep 'DROP TABLE' >> "${TMPFILE}"
@@ -43,4 +86,4 @@ mariadb --host="${host}" --user="${dbuser}" --password="${password}" "${database
 
 rm -f "${TMPFILE}"
 
-echo "All tables have been dropped from the database."
+showmessage "All tables have been dropped from database ${database}."
diff --git a/Joomla_scripts/jlistjoomlas b/Joomla_scripts/jlistjoomlas
--- a/Joomla_scripts/jlistjoomlas
+++ b/Joomla_scripts/jlistjoomlas
@@ -21,13 +21,13 @@ CONFIG_DIR="${HOME}/.config/phpdev"
 # path to the phpdev configuration file
 CONFIG_FILE="${CONFIG_DIR}/config"
 
-# Load configuration file defaults
-if [[ -f "${CONFIG_FILE}" ]]; then
-    source "${CONFIG_FILE}"
-else
-    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
-    exit 1
-fi   
+NOW=$(date +"%Y%m%d.%H%M%S")
+CSV_FILE="joomla_sites.${NOW}.csv"
+
+# show message function
+showmessage() {
+    echo -e "$1"
+}
 
 # Variables
 SHORT="no"
@@ -36,37 +36,33 @@ RELEASEVERSION=""
 
 # Display usage information
 usage() {
-    echo -e "${MYNAME} version ${VERSION}, written by Rene Kreijveld.\n"
-    echo -e "Usage: ${MYNAME} [-s] [-c] [-h] [-r release]\n"
+    echo -e "${MYNAME} ${VERSION}, written by René Kreijveld.\n"
+    echo -e "Usage: ${MYNAME} [-s] [-h] [-r release]\n"
     echo "-s Short. Only display path and Joomla version."
     echo "-r Release version. Only display information about Joomla sites with given release version (e.g., 1.5, 2.5, 3.4)."
-    echo "-c CSV. Output values in CSV format."
     echo -e "-h Help. Display this info.\n"
     exit 0
 }
 
 # Argument parsing
-while getopts "schr:" opt; do
+while getopts "shr:" opt; do
     case "${opt}" in
         s) SHORT="yes" ;;
-        c) CSV="yes" ;;
         r) RELEASEVERSION="$OPTARG" ;;
         h) usage ;;
         *) usage ;;
     esac
 done
 
-# Start output if not in CSV mode
-if [[ "${CSV}" == "no" ]]; then
-    if [[ "${SHORT}" == "no" ]]; then
-        echo -e "${MYNAME} version ${VERSION}, written by Rene Kreijveld.\n"
-    fi
-fi
+showmessage "${MYNAME} ${VERSION}\n"
 
-# Output CSV header if in CSV mode
-if [[ "${CSV}" == "yes" ]]; then
-    echo "\"path\",\"name\",\"version\",\"database\",\"dbuser\",\"password\",\"host\",\"prefix\""
-fi
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
 
 # Check if jfunctions script exists
 if [[ ! -f "${MYPATH}/jfunctions" ]]; then
@@ -77,13 +73,6 @@ fi
 # Scan directories for Joomla instances
 find "${ROOTFOLDER}" -maxdepth 2 -type d | while read -r DIR; do
     if [[ -f "${DIR}/configuration.php" ]]; then
-        # Possible Joomla found, get information
-        if [[ "${CSV}" == "no" ]]; then
-            if [[ "${SHORT}" == "no" ]]; then
-                echo "Possible Joomla found in ${DIR}"
-            fi
-        fi
-
         # Go to the directory where the site
         cd $DIR
 
@@ -92,30 +81,22 @@ find "${ROOTFOLDER}" -maxdepth 2 -type d | while read -r DIR; do
 
         # Filter by release version if provided
         if [[ -n "${RELEASEVERSION}" && "${RELEASEVERSION}" != "${jversion}" ]]; then
-            if [[ "${CSV}" == "no" && "${SHORT}" == "no" ]]; then
-                echo "Skipping, found version is ${jversion} and not ${RELEASEVERSION}."
-            fi
             continue
         fi
 
         # Output information
-        if [[ "${CSV}" == "yes" ]]; then
-            echo "\"${DIR}\",\"${sitename}\",\"${jversion}\",\"${database}\",\"${dbuser}\",\"${password}\",\"${host}\",\"${prefix}\""
+        if [[ "${SHORT}" == "no" ]]; then
+            printf "Sitename    : %s\n" "${sitenameclean}"
+            printf "Version     : %s\n" "${jversion}"
+            printf "DB Name     : %s\n" "${database}"
+            printf "DB User     : %s\n" "${dbuser}"
+            printf "DB Password : %s\n" "${password}"
+            printf "DB Host     : %s\n" "${host}"
+            printf "DB Prefix   : %s\n" "${prefix}"
+            printf "Path        : %s\n" "$(pwd)"
+            showmessage " "
         else
-            if [[ "${SHORT}" == "no" ]]; then
-                printf "Sitename    : %s\n" "${sitenameclean}"
-                printf "Version     : %s\n" "${jversion}"
-                printf "DB Name     : %s\n" "${database}"
-                printf "DB User     : %s\n" "${dbuser}"
-                printf "DB Password : %s\n" "${password}"
-                printf "DB Host     : %s\n" "${host}"
-                printf "DB Prefix   : %s\n" "${prefix}"
-                printf "Path        : %s\n" "$(pwd)"
-                echo ""
-            else
-                echo "Joomla found in ${DIR}"
-                echo -e "Version: ${jversion}\n"
-            fi
+            showmessage "Version: ${jversion}\n"
         fi
     fi
 done
