Code improvements

diff --git a/Joomla_scripts/jdbdumpall b/Joomla_scripts/jdbdumpall
--- a/Joomla_scripts/jdbdumpall
+++ b/Joomla_scripts/jdbdumpall
@@ -14,45 +14,45 @@
 # version
 VERSION=1.0
 
-# start folder where we start searching
-STARTDIR="/Users/$USER/Development/Sites"
+# folder for phpdev configuration
+CONFIG_DIR="${HOME}/.config/phpdev"
+# path to the phpdev configuration file
+CONFIG_FILE="${CONFIG_DIR}/config"
 
-# where to store backup files
-STOREPATH="/Users/$USER/Development/Backup/mysql"
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
 
 # display messages
 SILENT="no"
 
 # determine path of script
-MYPATH=$(
-    cd $(dirname ${0})
-    pwd -P
-)
-MYNAME=$(basename ${0})
+MYPATH=$(cd "$(dirname "$0")"; pwd -P)
+MYNAME=$(basename "$0")
 
 # check if folder for backup storage exists
-if [ ! -d "${STOREPATH}" ]; then
+if [ ! -d "${MARIADBBACKUP}" ]; then
     echo "Backup directory does not exist!"
     exit 1
 fi
 
 # display usage information
 usage() {
-    echo ""
-    echo "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
-    echo ""
-    echo "Usage: ${MYNAME} [-s] [-h]"
-    echo ""
+    echo -e "${MYNAME} version ${VERSION}, written by Rene Kreijveld.\n"
+    echo -e "Usage: ${MYNAME} [-s] [-h]\n"
     echo "-s Silent. Do not display any messages to standard output."
-    echo "-h Help. Display this info."
-    echo ""
+    echo -e "-h Help. Display this info.\n"
     exit 0
 }
 
 # show message function
 showmessage() {
     if [ "${SILENT}" == "no" ]; then
-        echo "$1"
+        echo -e "$1"
     fi
 }
 
@@ -74,7 +74,7 @@ done
 
 showmessage "${MYNAME} version ${VERSION}, written by Rene Kreijveld."
 
-for DIR in $(find ${STARTDIR} -maxdepth 4 -type d); do
+for DIR in $(find ${ROOTFOLDER} -maxdepth 4 -type d); do
     if [ -f ${DIR}/configuration.php ]; then
         # possible joomla found
         showmessage "Possible Joomla found at ${DIR}."
@@ -92,19 +92,15 @@ for DIR in $(find ${STARTDIR} -maxdepth 4 -type d); do
         NOW=$(date +"%Y%m%d-%H%M%S")
 
         # dump the database to a .sql file
-        if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} ${database} > ${STOREPATH}/${database}.${NOW}.sql; then
+        if mysqldump --skip-opt --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host=${host} --user=${dbuser} --password=${password} ${database} > ${MARIADBBACKUP}/${database}.${NOW}.sql; then
             showmessage "Database dump created for ${sitenameclean}"
         else
             showmessage "Error creating database dump."
             exit 1
         fi
 
-        # gzip database dump
-        showmessage "gzip ${database}.sql"
-        gzip -q ${STOREPATH}/${database}.${NOW}.sql
-
         showmessage "Database backup for ${sitenameclean} finished."
     fi
 done
 
-showmessage "Your database backups are ready in ${STOREPATH}."
+showmessage "Your database backups are ready in ${MARIADBBACKUP}."
