Added compact output

diff --git a/Joomla_scripts/joomlainfo b/Joomla_scripts/joomlainfo
--- a/Joomla_scripts/joomlainfo
+++ b/Joomla_scripts/joomlainfo
@@ -22,6 +22,54 @@ VERSION=1.5
 MYPATH=$(cd "$(dirname "${0}")" && pwd -P)
 MYNAME=$(basename "${0}")
 
+# folder for phpdev configuration
+CONFIG_DIR="${HOME}/.config/phpdev"
+# path to the phpdev configuration file
+CONFIG_FILE="${CONFIG_DIR}/config"
+
+# Display usage information
+usage() {
+    echo "${MYNAME} ${VERSION}, written by René Kreijveld."
+    echo -e "\nUsage: ${MYNAME} [-n <name>] [-c] [-h]\n"
+    echo "-n the name for the website to show the info of."
+    echo "-c show website info compact."
+    echo "-h help, display this info.\n"
+    exit 0
+}
+
+SHOW=""
+while getopts n:c opt; do
+    case "${opt}" in
+    n)
+        WEBSITE_NAME=$OPTARG
+        ;;
+    c)
+        SHOW="compact"
+        ;;
+    h)
+        usage
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        usage
+        ;;
+    esac
+done
+
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
+
+# Check if WEBSITE_NAME is not empty
+if [ ! -z "${WEBSITE_NAME}" ]; then
+    WEBSITE_FOLDER=${ROOTFOLDER}/${WEBSITE_NAME}
+    cd ${WEBSITE_FOLDER}
+fi
+
 # Include general functions
 if [[ ! -e "${MYPATH}/jfunctions" ]]; then
     echo "Error: Cannot continue. Script 'jfunctions' not found in ${MYPATH}."
@@ -32,14 +80,26 @@ else
 fi
 
 # Output information
-echo -e "${MYNAME} ${VERSION}\n"
-echo "This Joomla! website:"
-printf "Sitename    : %s\n" "${sitenameclean}"
-printf "Version     : %s\n" "${jversion}"
-printf "DB Name     : %s\n" "${database}"
-printf "DB User     : %s\n" "${dbuser}"
-printf "DB Password : %s\n" "${password}"
-printf "DB Host     : %s\n" "${host}"
-printf "DB Prefix   : %s\n" "${prefix}"
-printf "Path        : %s\n" "$(pwd)"
-echo ""
+if [ -z "${SHOW}" ]; then
+    echo -e "${MYNAME} ${VERSION}\n"
+    echo "This Joomla! website:"
+    printf "Sitename    : %s\n" "${sitenameclean}"
+    printf "Version     : %s\n" "${jversion}"
+    printf "DB Name     : %s\n" "${database}"
+    printf "DB User     : %s\n" "${dbuser}"
+    printf "DB Password : %s\n" "${password}"
+    printf "DB Host     : %s\n" "${host}"
+    printf "DB Prefix   : %s\n" "${prefix}"
+    printf "Path        : %s\n" "$(pwd)"
+    echo ""
+fi  
+
+if [ "${SHOW}" == "compact" ]; then
+    echo "VERSION=${jversion}"
+    echo "DATABASE=${database}"
+    echo "DBUSER=${dbuser}"
+    echo "PASSWORD=${password}"
+    echo "HOST=${host}"
+    echo "PREFIX=${prefix}"
+    echo "PATH=$(pwd)"
+fi  
