Added use of config file

diff --git a/Scripts/deldb b/Scripts/deldb
--- a/Scripts/deldb
+++ b/Scripts/deldb
@@ -8,12 +8,17 @@
 #
 # Version history
 # 1.0 Initial version
+# 1.1 Use config file
 
 # Variables 
 # version
-VERSION=1.0
+VERSION=1.1
 # name of this
 MYNAME=$(basename ${0})
+# folder for phpdev configuration
+CONFIG_DIR="${HOME}/.config/phpdev"
+# path to the phpdev configuration file
+CONFIG_FILE="${CONFIG_DIR}/config"
 
 # show message function
 showmessage() {
@@ -39,7 +44,7 @@ usage() {
 # Function to check if database exists
 database_exists() {
     DATABASE_NAME=$1
-    if mysql -u root -proot -e "use ${DATABASE_NAME}" 2>/dev/null; then
+    if mysql -u root -p${MARIADBPW} -e "use ${DATABASE_NAME}" 2>/dev/null; then
         return 0
     else
         return 1
@@ -71,6 +76,15 @@ while getopts ":d:sh" opt; do
 done
 
 showmessage "${MYNAME} version ${VERSION}, written by René Kreijveld."
+
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
+
 showmessage "Dropping database ${DATABASE_NAME}."
 
 # check if mandatory parameters are provided
@@ -85,5 +99,10 @@ if ! database_exists "${DATABASE_NAME}"; then
 fi
 
 # Drop the database
-mariadb -u root -proot -e "DROP DATABASE IF EXISTS \`${DATABASE_NAME}\`;"
-showmessage "Database ${DATABASE_NAME} dropped."
+if mariadb -u root -p${MARIADBPW} -e "DROP DATABASE IF EXISTS \`${DATABASE_NAME}\`;"; then
+    showmessage "Database ${DATABASE_NAME} dropped."
+else
+    echo "Error dropping database ${DATABASE_NAME}."
+    echo "The command was: mariadb -u root -p${MARIADBPW} -e \"DROP DATABASE IF EXISTS \`${DATABASE_NAME}\`;\""
+    exit 1
+fi
