Code improvements

diff --git a/Scripts/delsite b/Scripts/delsite
--- a/Scripts/delsite
+++ b/Scripts/delsite
@@ -18,6 +18,12 @@ MYNAME=$(basename ${0})
 MYPATH=$(cd $(dirname ${0}); pwd -P)
 # nginx folder for website configurations
 NGINX_CONF_DIR=/opt/homebrew/etc/nginx/servers
+# apache etc dir
+APACHE_DIR=/opt/homebrew/etc/httpd
+# apache etc dir
+APACHE_VHOSTS_CONF=${APACHE_DIR}/extra/httpd-vhosts.conf
+# apache folder for website configurations
+APACHE_CONF_DIR=${APACHE_DIR}/vhosts
 # Websites root
 SITE_ROOT="/Users/$USER/Development/Sites"
 # folder for phpdev configuration
@@ -28,39 +34,25 @@ CONFIG_FILE="${CONFIG_DIR}/config"
 # show message function
 showmessage() {
     if [ "${SILENT}" == "no" ]; then
-        echo "$1"
+        echo -e "$1"
     fi
 }
 
 # display usage information
 usage() {
-    echo ""
-    echo "${MYNAME} version ${VERSION}, written by René Kreijveld."
-    echo ""
-    echo "Usage: ${MYNAME} -n <name> [-d] [-b] [-s] [-h]"
-    echo ""
+    echo -e "${MYNAME} version ${VERSION}, written by René Kreijveld.\n"
+    echo -e "Usage: ${MYNAME} -n <name> [-d] [-s] [-h]\n"
     echo " -n the name for the website (input without spaces, mandatory)."
     echo " -d also drop the database (optional)."
-    echo " -b backup website and database before deleting (optional)."
     echo " -s silent, no messages will be shown (optional)."
-    echo " -h display this help."
-    echo ""
+    echo -e " -h display this help.\n"
     exit 0
-}
-
-# Function to check if the site name contains spaces
-contains_spaces() {
-    if [[ "$1" =~ \  ]]; then
-        return 0
-    else
-        return 1
-    fi
 }
 
 # Function to check if database exists
 database_exists() {
     DATABASE_NAME=$1
-    if mysql -u root -proot -e "use ${DATABASE_NAME}" 2>/dev/null; then
+    if mariadb -u root -proot -e "use ${DATABASE_NAME}" 2>/dev/null; then
         return 0
     else
         return 1
@@ -69,7 +61,6 @@ database_exists() {
 
 # Parse command line arguments
 SILENT="no"
-BACKUP="no"
 DBDELETE="no"
 while getopts ":n:dbsh" opt; do
     case ${opt} in
@@ -78,9 +69,6 @@ while getopts ":n:dbsh" opt; do
         ;;
     d)
         DBDELETE="yes"
-        ;;
-    b)
-        BACKUP="yes"
         ;;
     s)
         SILENT="yes"
@@ -117,51 +105,34 @@ if [ -z "${WEBSITE_NAME}" ]; then
     usage
 fi
 
-# check if the site name contains spaces
-if contains_spaces "${WEBSITE_NAME}"; then
-    echo "Error: Site name '$name' contains spaces. Please provide a name without spaces."
-    exit 1
-fi
-
 # Check if the site folder already exists
 SITE_FOLDER="${ROOTFOLDER}/${WEBSITE_NAME}"
 if [ ! -d "${SITE_FOLDER}" ]; then
-    echo "Error: The website folder '${SITE_FOLDER}' not found."
+    echo "Error: website folder '${SITE_FOLDER}' not found, exiting"
     exit 1
+fi
+
+# Request confirmation
+if [ "${DBDELETE}" == "yes" ]; then
+    read -p "You are about to delete a website and database. Press Enter to continue, press Ctrl-C to abort."
+else
+    read -p "You are about to delete a website. Press Enter to continue, press Ctrl-C to abort."
 fi
 
 # Get website information
 cd ${SITE_FOLDER}
-# include general functions
-if [ ! -e ${MYPATH}/jfunctions ]
-then
-    echo ""
-    echo "Cannot continue: script jfunctions not found."
-    echo ""
-    exit 1
-else
-    # gather joomla information
-    . ${MYPATH}/jfunctions
-fi
-
-if [ "${BACKUP}" == "yes" ]; then
-    # Create database dump
-    showmessage "Create website database dump for backup."
-    if ! mysqldump --skip-opt --extended-insert=FALSE --add-drop-table --add-locks --create-options --disable-keys --lock-tables --quick --set-charset --host="${host}" --user="${dbuser}" --password="${password}" "${database}" > "${database}.sql"; then
-        showmessage "Error creating database dump."
-        exit 1
-    fi
-    cd ${ROOTFOLDER}
-    NOW=$(date +"%Y%m%d.%H%M%S")
-    showmessage "Create website backup."
-    tar czf ${WEBSITE_NAME}.${NOW}.tgz ${WEBSITE_NAME}
-    showmessage "Website backup is ready at: ${ROOTFOLDER}/${WEBSITE_NAME}.${NOW}.tgz."
-fi
-
 if [ "${DBDELETE}" == "yes" ]; then
-    # Drop the database
-    showmessage "Dropping database ${database}."
-    deldb -d ${database} -s
+    # include general functions
+    if [ ! -e ${MYPATH}/jfunctions ]; then
+        echo -e "Cannot continue: script jfunctions not found.\n"
+        exit 1
+    else
+        # gather joomla information
+        . ${MYPATH}/jfunctions
+        # Drop the database
+        showmessage "Dropping database ${database}."
+        deldb -d ${database} -s
+    fi
 fi
 
 # Delete website folder
@@ -173,6 +144,20 @@ rm -rf ${SITE_FOLDER}
 NGINX_CONF_FILE=${NGINX_CONF_DIR}/${WEBSITE_NAME}.conf
 rm -f ${NGINX_CONF_FILE}
 
-# Restart NginX
-showmessage "Restarting nginx, you may need to enter your password."
-sudo brew services restart nginx
+# Delete the Apache configuration
+APACHE_CONF_FILE=${APACHE_CONF_DIR}/${WEBSITE_NAME}.conf
+rm -f ${APACHE_CONF_FILE}
+DELTXT="IncludeOptional ${APACHE_CONF_FILE}"
+sed -i '' "s|${DELTXT}||g" ${APACHE_VHOSTS_CONF}
+
+if [ "${WEBSERVER}" == "nginx" ]; then
+    # Restart NginX
+    showmessage "Restarting nginx."
+    sudo brew services restart nginx
+fi
+
+if [ "${WEBSERVER}" == "apache" ]; then
+    # Restart Apache
+    showmessage "Restarting apache."
+    brew services restart httpd
+fi
