Modified start. top, restart scripts to use config file

diff --git a/Scripts/restartdev b/Scripts/restartdev
--- a/Scripts/restartdev
+++ b/Scripts/restartdev
@@ -9,14 +9,32 @@
 # Version history
 # 1.0 Initial version
 
+CONFIG_DIR="${HOME}/.config/phpdev"
+CONFIG_FILE="${CONFIG_DIR}/config"
+
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
+
 # Restart Dnsmasq
 /usr/local/bin/restartdnsmasq
 
 # Restart PHP-FPM
 /usr/local/bin/restartphpfpm
 
-# Restart NginX
-/usr/local/bin/restartnginx
+if [ "${WEBSERVER}" == "apache" ]; then
+    # Restart Apache
+    /usr/local/bin/restartapache
+fi
+
+if [ "${WEBSERVER}" == "nginx" ]; then
+    # Restart NginX
+    /usr/local/bin/restartnginx
+fi
 
 # Restart MariaDB
 /usr/local/bin/restartmariadb
diff --git a/Scripts/startdev b/Scripts/startdev
--- a/Scripts/startdev
+++ b/Scripts/startdev
@@ -9,11 +9,21 @@
 # Version history
 # 1.0 Initial version
 
-echo "Starting NginX - MariaDB - PHP development environment services."
+CONFIG_DIR="${HOME}/.config/phpdev"
+CONFIG_FILE="${CONFIG_DIR}/config"
+
+echo "Starting Apache/NginX - MariaDB - PHP development environment services."
 echo "These services will run in the background and will automatically restart on system reboot."
-echo "When the Password: prompt appears, enter your password to allow the services to run."
-echo " "
+echo -e "When the Password: prompt appears, enter your password to allow the services to run.\n"
 echo "To permanently stop the services, run the stopdev script."
+
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
 
 # Start Dnsmasq
 /usr/local/bin/startdnsmasq
@@ -21,8 +31,15 @@ echo "To permanently stop the services, run the stopdev script."
 # Start PHP-FPM
 /usr/local/bin/startphpfpm
 
-# Start NginX
-/usr/local/bin/startnginx
+if [ "${WEBSERVER}" == "apache" ]; then
+    # Start Apache
+    /usr/local/bin/startapache
+fi
+
+if [ "${WEBSERVER}" == "nginx" ]; then
+    # Start NginX
+    /usr/local/bin/startnginx
+fi
 
 # Start MariaDB
 /usr/local/bin/startmariadb
diff --git a/Scripts/stopdev b/Scripts/stopdev
--- a/Scripts/stopdev
+++ b/Scripts/stopdev
@@ -6,9 +6,20 @@
 # This script is free software; you may redistribute it and/or modify it.
 # This script comes without any warranty. Use it at your own risk.
 
-echo "Stopping NginX - MariaDB - PHP development environment services."
+CONFIG_DIR="${HOME}/.config/phpdev"
+CONFIG_FILE="${CONFIG_DIR}/config"
+
+echo "Stopping Apache/NginX - MariaDB - PHP development environment services."
 echo "The background services will now be stopped and will not automatically restart on system reboot."
 echo "When the Password: prompt appears, enter your password to allow the services to be stopped."
+
+# Load configuration file defaults
+if [[ -f "${CONFIG_FILE}" ]]; then
+    source "${CONFIG_FILE}"
+else
+    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
+    exit 1
+fi   
 
 # Stop Mailpit
 /usr/local/bin/stopmailpit
@@ -16,8 +27,15 @@ echo "When the Password: prompt appears, enter your password to allow the servic
 # Stop MariaDB
 /usr/local/bin/stopmariadb
 
-# Stop NginX
-/usr/local/bin/stopnginx
+if [ "${WEBSERVER}" == "apache" ]; then
+    # Stop Apache
+    /usr/local/bin/stopapache
+fi
+
+if [ "${WEBSERVER}" == "nginx" ]; then
+    # Stop NginX
+    /usr/local/bin/stopnginx
+fi
 
 # Stop PHP-FPM
 /usr/local/bin/stopphpfpm
@@ -25,5 +43,4 @@ echo "When the Password: prompt appears, enter your password to allow the servic
 # Stop Dnsmasq
 /usr/local/bin/stopdnsmasq
 
-echo " "
-echo "To start the services again, run the stopdev script."
+echo -e "\nTo start the services again, run the startdev script."
